#pragma once

#define ESP_CAM_WIFI_SSID "YOUR_WIFI_SSID"
#define ESP_CAM_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define ESP_CAM_HOSTNAME "esp32-cam"

#define ESP_CAM_DIRECT_AP_SSID "ESP32-CAM-Stream"
#define ESP_CAM_DIRECT_AP_PASSWORD "YOUR_DIRECT_AP_PASSWORD"
